// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RailWayWpfApp.Data;

#nullable disable

namespace RailWayWpfApp.Migrations
{
    [DbContext(typeof(RailWayDB))]
    partial class RailWayDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RailWayWpfApp.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoginId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("RailWayWpfApp.Models.RailWayTable", b =>
                {
                    b.Property<int>("RailWayTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RailWayTableId"));

                    b.Property<DateTime>("MahalliyVaqt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RailWayTableId");

                    b.ToTable("RailWayTables");
                });

            modelBuilder.Entity("RailWayWpfApp.Models.Registratsiya", b =>
                {
                    b.Property<int>("RegistratsiyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistratsiyaId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepeatPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RegistratsiyaId");

                    b.ToTable("Registratsiyas");
                });
#pragma warning restore 612, 618
        }
    }
}
